import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import { createVuetify } from 'vuetify'
import {
  VAlert,
  VApp,
  VAppBar,
  VAppBarNavIcon,
  VAppBarTitle,
  VAutocomplete,
  VAvatar,
  VBtn,
  VCard,
  VCardActions,
  VCardItem,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VCol,
  VContainer,
  VDataTable,
  VDialog,
  VDivider,
  VIcon,
  VImg,
  VLabel,
  VList,
  VListItem,
  VListItemAction,
  VListItemSubtitle,
  VListItemTitle,
  VMain,
  VMenu,
  VNavigationDrawer,
  VProgressCircular,
  VProgressLinear,
  VRow,
  VSelect,
  VSheet,
  VSpacer,
  VSwitch,
  VTab,
  VTabs,
  VTabsWindow,
  VTabsWindowItem,
  VTextarea,
  VTextField,
  VTooltip,
  VDatePicker,
  VTimePicker,
  VNumberInput,
} from 'vuetify/components'
import * as directives from 'vuetify/directives'
// @ts-ignore
import { aliases, mdi } from 'vuetify/lib/iconsets/mdi'
import { VDateInput } from 'vuetify/labs/VDateInput'

export const themes = {
  light: {
    dark: false,
    colors: {
      primary: '#691C32',
      secondary: '#BC955C',
      info: '#6F7271',
      success: '#235B4E',
      warning: '#FB8C00',
      error: '#C62828',
    },
  },
}

export const vuetify = createVuetify({
  theme: {
    themes,
    variations: {
      colors: ['primary', 'secondary'],
      lighten: 5,
      darken: 4,
    },
    defaultTheme: 'light',
  },
  icons: {
    defaultSet: 'mdi',
    aliases,
    sets: { mdi },
  },
  components: {
    VAlert,
    VApp,
    VAppBar,
    VAppBarNavIcon,
    VAppBarTitle,
    VAutocomplete,
    VAvatar,
    VBtn,
    VCard,
    VCardActions,
    VCardItem,
    VCardText,
    VCardTitle,
    VCheckbox,
    VChip,
    VCol,
    VContainer,
    VDataTable,
    VDialog,
    VDivider,
    VIcon,
    VImg,
    VLabel,
    VList,
    VListItem,
    VListItemAction,
    VListItemSubtitle,
    VListItemTitle,
    VMain,
    VMenu,
    VNavigationDrawer,
    VProgressCircular,
    VProgressLinear,
    VRow,
    VSelect,
    VSheet,
    VSpacer,
    VSwitch,
    VTab,
    VTabs,
    VTabsWindow,
    VTabsWindowItem,
    VTextarea,
    VTextField,
    VTooltip,
    VTimePicker,
    VDateInput,
    VDatePicker,
    VNumberInput,
  },
  directives,
  defaults: {
    VAutocomplete: {
      density: 'compact',
      variant: 'outlined',
      persistentPlaceholder: true,
      noDataText: 'No hay datos para mostrar',
    },
    VBtn: {
      variant: 'elevated',
      size: 'small',
    },
    VCheckbox: {
      color: 'primary',
      density: 'compact',
    },
    VCombobox: {
      color: 'primary',
      density: 'compact',
      variant: 'outlined',
      persistentPlaceholder: true,
      noDataText: 'No hay datos para mostrar',
    },
    VDataTable: {
      noDataText: 'No hay datos para mostrar',
    },
    VFileInput: {
      density: 'compact',
      variant: 'outlined',
      persistentPlaceholder: true,
      chips: true,
    },
    VSelect: {
      density: 'compact',
      variant: 'outlined',
      persistentPlaceholder: true,
      noDataText: 'No hay datos para mostrar',
    },
    VSwitch: {
      color: 'primary',
    },
    VTextarea: {
      color: 'primary',
      density: 'compact',
      variant: 'outlined',
      persistentPlaceholder: true,
    },
    VTextField: {
      color: 'primary',
      density: 'compact',
      variant: 'outlined',
      persistentPlaceholder: true,
    },
    VTimePicker: {
      color: 'primary',
      title: 'Seleccionar hora',
    },
    VDateInput: {
      color: 'primary',
      density: 'compact',
      variant: 'outlined',
      persistentPlaceholder: true,
      cancelText: 'Cancelar',
      okText: 'Aceptar',
    },
    VDatePicker: {
      color: 'primary',
    },
    VNumberInput: {
      color: 'primary',
      density: 'compact',
      variant: 'outlined',
      persistentPlaceholder: true,
      inset: true,
      controlVariant: 'stacked',
    },
  },
})
