<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>4f65f45a-37c0-4034-ba4c-8af68e4f067a</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="ProgramCopy.cs" />
    <Compile Remove="Startup - Copia.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Files\Base.txt" />
    <None Remove="HtmlTemplates\NotificacionAPArchivos.html" />
    <None Remove="HtmlTemplates\NotificacionCopadeArchivos.html" />
    <None Remove="HtmlTemplates\NotificacionDesvioFirma.html" />
    <None Remove="HtmlTemplates\NotificacionDesvioFirmaError.html" />
    <None Remove="HtmlTemplates\NotificacionFacturaAPErrorEmail.html" />
    <None Remove="HtmlTemplates\NotificacionFacturaAPExitoEmail.html" />
    <None Remove="HtmlTemplates\NotificacionFacturaCOPADE.html" />
    <None Remove="HtmlTemplates\NotificacionFacturaErrorEmail.html" />
    <None Remove="HtmlTemplates\NotificacionFacturaExitoEmail.html" />
    <None Remove="HtmlTemplates\NotificacionFirmasAP.html" />
    <None Remove="HtmlTemplates\NotificacionFirmasCOPADE.html" />
    <None Remove="HtmlTemplates\NotificacionFirmasES.html" />
    <None Remove="HtmlTemplates\NotificacionFirmasOS.html" />
    <None Remove="HtmlTemplates\NotificacionFirmasPP.html" />
    <None Remove="HtmlTemplates\NotificacionFirmasRE.html" />
  </ItemGroup>
  <ItemGroup>
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\IISProfile-des.pubxml" />
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\IISProfile-qa.pubxml" />
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\SettingsDEV.pubxml" />
    <_WebToolingArtifacts Remove="Properties\PublishProfiles\SettingsQA.pubxml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Files\Base.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionAPArchivos.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionCopadeArchivos.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionDesvioFirmaError.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFacturaAPErrorEmail.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFacturaAPExitoEmail.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFacturaCOPADE.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFacturaErrorEmail.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFacturaExitoEmail.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionDesvioFirma.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFirmasAP.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFirmasCOPADE.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFirmasES.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFirmasPP.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFirmasOS.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="HtmlTemplates\NotificacionFirmasRE.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.System" Version="8.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="8.0.0" />
    <PackageReference Include="BarcodeLib" Version="3.0.3" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Humanizer.Core.es" Version="2.14.1" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="8.0.5" />
    <PackageReference Include="itext7" Version="8.0.5" />
    <PackageReference Include="itext7.pdfhtml" Version="5.0.5" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="NuGet.Common" Version="6.12.1" />
    <PackageReference Include="NuGet.Packaging" Version="6.12.1" />
    <PackageReference Include="NuGet.Protocol" Version="6.12.1" />
    <PackageReference Include="NPOI" Version="2.6.2" />
    <PackageReference Include="QRCoder" Version="1.4.2" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.1" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="6.5.0" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.Identity.Abstractions" Version="9.2.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="3.10.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="8.0.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BERecepcion.Core\BERecepcion.Core.csproj" />
    <ProjectReference Include="..\BERecepcion.Infraestructura\BERecepcion.Infraestructura.csproj" />
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Connected Services\" />
    <Folder Include="Logs\" />
    <Folder Include="TemporalPDF\" />
    <Folder Include="Views\Copade\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="HtmlHelpers\ControllerExtensions.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Views\FacturaPDF\Comprobante.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\FacturaPDF\Factura40.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\FacturaPDF\Factura.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\PCORP\IndexPCorp.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\PEP\IndexPep.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\PTRI\IndexPtri.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\Reception\PCORP\Index.cshtml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="Fuentes\arial_narrow_7.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fuentes\fa-regular-400.eot">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fuentes\fa-regular-400.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fuentes\fa-regular-400.ttf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fuentes\fa-regular-400.woff">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fuentes\Fuentes.css">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Fuentes\PIXEARG_.eot">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TemporalPDF\prueba.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties appsettings_1json__JsonSchema="" />
    </VisualStudio>
  </ProjectExtensions>
</Project>